name: Split releases

on:
  push:
    tags:
      - 'v*'
#  release:
#    types: ['published']

concurrency:
  group: split

env:
  GH_TOKEN: ${{ secrets.SUBSPLIT_WRITE_ACCESS }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { folder: actor, repo: module-actor }
          - { folder: agent, repo: module-agent }
          - { folder: bootloader, repo: module-bootloader }
          - { folder: migration, repo: module-migration }
          - { folder: relay, repo: module-relay }
          - { folder: security, repo: module-security }
          - { folder: terminal, repo: module-terminal }
          - { folder: views, repo: module-views }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          split_sha=`git subtree split --prefix=src/${{ matrix.package.folder }}`
          repo_url="https://${{ secrets.SUBSPLIT_WRITE_ACCESS }}@github.com/wippyai/${{ matrix.package.repo }}.git"
          if [ -z $(git ls-remote --tags "$repo_url" | grep "$split_sha") ]; then \
             git tag -a ${{ github.ref_name }} -m "Release ${{ github.ref_name }}" "$split_sha"; \
          fi
#          if [ -z $(git ls-remote --tags "$repo_url" | grep "$split_sha") ]; then \
#            gh release create ${{ github.ref_name }} \
#              --repo wippyai/${{ matrix.package.repo }} \
#              --target "$split_sha" \
#              --generate-notes \
#              --notes '[Full release information in Typhoon monorepo](https://github.com/wippyai/typhoon/releases/tag/${{ github.ref_name }}).'; \
#          fi
