name: Split releases

on:
  release:
    types: ['published']

concurrency:
  group: split

env:
  GH_TOKEN: ${{ secrets.SUBSPLIT_WRITE_ACCESS }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - { folder: actor, repo: module-actor }
          - { folder: agent, repo: module-agent }
          - { folder: bootloader, repo: module-bootloader }
          - { folder: migration, repo: module-migration }
          - { folder: relay, repo: module-relay }
          - { folder: security, repo: module-security }
          - { folder: terminal, repo: module-terminal }
          - { folder: test, repo: module-test }
          - { folder: views, repo: module-views }
          - { folder: llm, repo: module-llm }
          - { folder: usage, repo: module-usage }
          - { folder: docs, repo: module-docs }
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Publishing
        uses: wippyai/action-module-release@main
        with:
          directory: src/${{ matrix.package.folder }}
          tag: ${{ github.ref_name }}
          username: ${{ secrets.WIPPY_USERNAME }}
          password: ${{ secrets.WIPPY_PASSWORD }}

          # Deprecated:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: ${{ github.repository }}
