name: Split commits

on:
  push:
    branches: ['main', '*.*']

concurrency:
  group: split

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - { folder: actor, repo: module-actor }
          - { folder: agent, repo: module-agent }
          - { folder: bootloader, repo: module-bootloader }
          - { folder: migration, repo: module-migration }
          - { folder: relay, repo: module-relay }
          - { folder: security, repo: module-security }
          - { folder: terminal, repo: module-terminal }
          - { folder: test, repo: module-test }
          - { folder: views, repo: module-views }
          - { folder: llm, repo: module-llm }
          - { folder: usage, repo: module-usage }
          - { folder: docs, repo: module-docs }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          repo_url="https://${{ secrets.SUBSPLIT_WRITE_ACCESS }}@github.com/wippyai/${{ matrix.package.repo }}.git"
          git subtree push --prefix src/${{ matrix.package.folder }} "$repo_url" ${{ github.ref_name }}
